woowacourse-teams/2023-dong-gle

frontend/src/index.tsx, frontend/webpack.config.js
=> [FE] chore: 절대 경로 설정 수정

frontend/.eslintrc
- close #31 
- eslint 현상 수정
- 1
-
=> [FE] fix: eslint 적용 되지 않는 현상 수정

backend/src/main/java/org/donggle/backend/domain/Block.java, backend/src/main/java/org/donggle/backend/domain/BlockType.java, backend/src/main/java/org/donggle/backend/domain/Style.java, backend/src/main/java/org/donggle/backend/domain/content/CodeBlockContent.java, backend/src/main/java/org/donggle/backend/domain/content/Content.java, backend/src/main/java/org/donggle/backend/domain/content/ImageContent.java, backend/src/main/java/org/donggle/backend/domain/content/NormalContent.java
- close #47 
- 기본 엔티티 리팩토링
- 12
-
=> refactor: 기본 엔티티 리팩토링

frontend/src/apis/fetch.ts, frontend/src/apis/writings.ts, frontend/src/hooks/@common/useGetQuery.ts, frontend/src/hooks/@common/useMutationQuery.ts
=> [FE] feat: API 추상화 로직 구현

frontend/src/apis/writings.ts, frontend/src/types/apis/writings.ts
- close #55 
- writings api 타입 추가
- writings api 메서드 리팩터링
- 0
-
=> [FE] refactor: writings API 타입 추가 및 관련 메서드 수정

frontend/src/components/@common/Spinner/Spinner.stories.tsx, frontend/src/components/@common/Spinner/Spinner.tsx, frontend/src/styles/animation.ts
- close #16 
- `styles/animation.ts`에 `rotation` 애니메이션 추가
- `Spinner` 컴포넌트 구현
- `Spinner` 스토리 작성
- 2
스피너는 rem으로 하기에는 그냥 공통 컴포넌트라 px을 사용했어요
=> [FE] feat: `Spinner` 컴포넌트 구현

frontend/src/apis/writings.ts, frontend/src/mocks/handlers.ts
- close #14
- 글 생성(POST) API mocking
- `apis/writings.ts`에 body에 body 객체 한 번 더 감싸져서 오는 현상 수정
- 0.2(-1.8)
- 응답으로 Location에 글 id가 오는데 1로 고정했어요
- apis/writings 수정했으니 확인부탁드려요
=> [FE] feat: 글 생성 API mocking

frontend/src/mocks/handlers.ts
- close #27 
- 1.5 시간 덜 걸림
- 아직 발행 로직이 머지되지 않아 직접 테스트는 못해봤습니다.
=> [FE] feat: 글 발행 POST API mocking 구현

backend/src/main/java/org/donggle/backend/domain/Block.java, backend/src/main/java/org/donggle/backend/domain/BlockType.java, backend/src/main/java/org/donggle/backend/domain/Style.java, backend/src/main/java/org/donggle/backend/domain/StyleType.java, backend/src/main/java/org/donggle/backend/domain/content/CodeBlockContent.java, backend/src/main/java/org/donggle/backend/domain/content/Content.java, backend/src/main/java/org/donggle/backend/domain/content/NormalContent.java, backend/src/main/java/org/donggle/backend/domain/parser/MarkDownParser.java, backend/src/main/java/org/donggle/backend/domain/parser/MarkDownStyleParser.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownStyleParserTest.java
- close #32 
-  각 줄 맨 앞의 type 구분자를 분석해 Block의 BlockType 분석 기능 구현
-  정규표현식을 통해 줄 글의 Style들을 추출 기능 구현
-  추출한 스타일, 타입, 줄 글을 Block 객체 맵핑 기능 구현
- 16시간
- 기능만 구현했고 추후에 리팩토링 진행하겠습니다!
=> [BE] feat: 텍스트 파싱 기능 구현

backend/src/main/java/org/donggle/backend/domain/BlockType.java, backend/src/main/java/org/donggle/backend/domain/content/CodeBlockContent.java, backend/src/main/java/org/donggle/backend/domain/parser/MarkDownParser.java, backend/src/main/java/org/donggle/backend/domain/parser/MarkDownStyleParser.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownStyleParserTest.java
- close #64 
- 개행을 기준으로 Block을 나누는 기능구현
- MarkDownParser리팩터링
- 3
=>  [BE] feat , refactor:  개행을 기준으로 각 줄을 읽는 기능 구현 및 Parser 리팩터링 

backend/build.gradle, backend/src/main/java/org/donggle/backend/application/service/medium/MediumApiService.java, backend/src/main/java/org/donggle/backend/application/service/medium/dto/MediumPublishData.java, backend/src/main/java/org/donggle/backend/application/service/medium/dto/MediumPublishRequest.java, backend/src/main/java/org/donggle/backend/application/service/medium/dto/MediumPublishResponse.java, backend/src/main/java/org/donggle/backend/application/service/medium/dto/MediumUserData.java, backend/src/main/java/org/donggle/backend/application/service/medium/dto/MediumUserResponse.java
- close #73 
- `MediumApiService` 구현
- 30 분
=> [BE] feat: Medium API 서비스 구현

backend/src/main/java/org/donggle/backend/application/UploadWritingService.java, backend/src/main/java/org/donggle/backend/application/repository/ContentRepository.java, backend/src/main/java/org/donggle/backend/domain/Member.java, backend/src/main/java/org/donggle/backend/domain/Style.java, backend/src/main/java/org/donggle/backend/domain/Writing.java, backend/src/main/java/org/donggle/backend/domain/content/CodeBlockContent.java, backend/src/main/java/org/donggle/backend/domain/content/Content.java, backend/src/main/java/org/donggle/backend/domain/content/ImageContent.java, backend/src/main/java/org/donggle/backend/domain/content/NormalContent.java, backend/src/main/java/org/donggle/backend/exception/notfound/MemberNotFoundException.java, backend/src/main/java/org/donggle/backend/ui/UploadApiController.java, backend/src/main/resources/application.yaml, backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlRendererTest.java
- close #70 
- 파싱된 객체들을 영속화
- 2
-
=> [BE] feat: 글 영속화 로직 구현

backend/src/main/java/org/donggle/backend/application/WritingService.java, backend/src/main/java/org/donggle/backend/application/repository/BlockRepository.java, backend/src/main/java/org/donggle/backend/domain/content/NormalContent.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlRenderer.java, backend/src/main/java/org/donggle/backend/dto/WritingResponse.java, backend/src/main/java/org/donggle/backend/exception/notfound/WritingNotFoundException.java, backend/src/main/java/org/donggle/backend/ui/WritingController.java
- close #37 
- 글 조회 API 구현
- 2시간
-
=> [BE] feat: 글 조회 API 구현

backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlType.java
- close #77 
- HtmlType의 CODE_BLOCK startTag 수정
- 5분
=> [BE] refactor: 렌더링 기능 수정

backend/src/main/java/org/donggle/backend/application/repository/BlogRepository.java, backend/src/main/java/org/donggle/backend/application/repository/BlogWritingRepository.java, backend/src/main/java/org/donggle/backend/application/service/PublishService.java, backend/src/main/java/org/donggle/backend/application/service/medium/dto/MediumPublishData.java, backend/src/main/java/org/donggle/backend/domain/BlogType.java, backend/src/main/java/org/donggle/backend/domain/BlogWriting.java, backend/src/main/java/org/donggle/backend/domain/Writing.java, backend/src/main/java/org/donggle/backend/dto/PublishRequest.java, backend/src/main/java/org/donggle/backend/exception/notfound/BlogNotFoundException.java, backend/src/main/java/org/donggle/backend/ui/WritingController.java
- closed: #40 
- 글 발행 API 구현
- `기존 예상 시간` -> `실제 소요 시간`
-
=> [BE] feat: 글 발행 API 구현

backend/src/main/java/org/donggle/backend/application/WritingService.java, backend/src/main/java/org/donggle/backend/application/repository/BlogWritingRepository.java, backend/src/main/java/org/donggle/backend/application/service/PublishService.java, backend/src/main/java/org/donggle/backend/domain/BlogWriting.java, backend/src/main/java/org/donggle/backend/domain/Writing.java, backend/src/main/java/org/donggle/backend/dto/WritingPropertiesResponse.java, backend/src/main/java/org/donggle/backend/dto/WritingResponse.java, backend/src/main/java/org/donggle/backend/ui/WritingController.java
- close #39 
- 글 정보 조회 API 구현
- 글 정보 조회 API 명세 변경 및 BlogWriting 객체 필드 변경
- 2
=> [BE] feat: 글 정보 조회 API 기능 구현

backend/src/main/java/org/donggle/backend/application/WritingService.java, backend/src/main/java/org/donggle/backend/application/repository/BlogRepository.java, backend/src/main/java/org/donggle/backend/application/service/PublishService.java, backend/src/main/java/org/donggle/backend/application/service/medium/MediumApiService.java, backend/src/main/java/org/donggle/backend/application/service/medium/dto/MediumPublishData.java, backend/src/main/java/org/donggle/backend/application/service/medium/exception/MediumBadRequestException.java, backend/src/main/java/org/donggle/backend/application/service/medium/exception/MediumException.java, backend/src/main/java/org/donggle/backend/application/service/medium/exception/MediumForbiddenException.java, backend/src/main/java/org/donggle/backend/application/service/medium/exception/MediumInternalServerError.java, backend/src/main/java/org/donggle/backend/application/service/medium/exception/MediumUnAuthorizedException.java, backend/src/main/java/org/donggle/backend/domain/Blog.java, backend/src/main/java/org/donggle/backend/dto/PublishedDetailResponse.java
- close #82 
- 글 발행 API 리펙토링
- 1
=> [BE] refactor: 글 발행 API 리펙토링

frontend/package.json, frontend/public/index.html, frontend/src/components/@common/Divider/Divider.tsx, frontend/src/components/WritingViewer/WritingViewer.tsx, frontend/src/mocks/writingContentMock.ts, frontend/src/pages/Layout/Layout.tsx, frontend/src/pages/WritingPage/WritingPage.tsx, frontend/yarn.lock
- close #61
-  html 태그별 스타일 추가
-  highlight.js 적용
- 8(+0)
-
=> [FE] feat: `WritingViewer` 컴포넌트 내부 태그 별 스타일 추가

frontend/package.json, frontend/src/hooks/@common/useMutation.ts, frontend/src/hooks/useFileUpload.ts, frontend/src/index.tsx, frontend/src/mocks/handlers/writing.ts, frontend/src/pages/Layout/Layout.tsx, frontend/src/pages/WritingPage/WritingPage.tsx, frontend/src/routes/Router.tsx, frontend/webpack.config.js, frontend/yarn.lock
- close #81
- react-query 설치 및 설정
- 업로드 성공 시 글 가져오는 기능을 구현한다.
- 2(+0)
-
=> [FE] feat: 업로드 성공 시 `WritingViewer`를 보여주는 기능 구현

backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlRendererTest.java
=> [BE] refactor: test코드 수정

backend/src/main/java/org/donggle/backend/config/InitData.java, backend/src/main/java/org/donggle/backend/domain/blog/Blog.java
- close #85 
- dev와 test 환경에서 Blog 테블의 레코드 자동 추가
- 0
- Blog 테이블에 MEDIUM과 TISTORY를 자동으로 삽입한다.
=> [BE] feat: db 초기 데이터 삽입 기능 구현

backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownStyleParser.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownStyleParserTest.java
- close #97 
- markDown파싱 기능 리팩터링
- 0.01
=> [BE] refactor: MarkDown parser 리팩터링

frontend/.babelrc.json, frontend/.eslintrc, frontend/__tests__/hello.tsx, frontend/jest.config.js, frontend/package.json, frontend/src/mocks/svg.ts, frontend/tsconfig.json, frontend/yarn.lock
- close #106
-  RTL 설치
- RTL 설정
- RTL에서 svg를 이용할 수 있도록 설정
- 4(+0)
-
=> [FE] chore: `react-testing-library` 설치 및 설정

backend/src/main/resources/application-prod.yaml
- close #110 
- property에서 h2 제거
- mysql 유저 생성 후 github secrets에 변수들 추가
- 30
-
=> [BE] chore: mysql db 연결을 위한 h2 설정 제거

backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownParser.java, backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownStyleParser.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlRenderer.java, backend/src/main/java/org/donggle/backend/domain/writing/BlockType.java, backend/src/main/java/org/donggle/backend/domain/writing/StyleType.java, backend/src/main/java/org/donggle/backend/domain/writing/content/CodeBlockContent.java, backend/src/main/java/org/donggle/backend/domain/writing/content/ImageCaption.java, backend/src/main/java/org/donggle/backend/domain/writing/content/ImageContent.java, backend/src/main/java/org/donggle/backend/domain/writing/content/ImageUrl.java, backend/src/main/java/org/donggle/backend/domain/writing/content/Language.java, backend/src/main/java/org/donggle/backend/domain/writing/content/RawText.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownStyleParserTest.java, backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlRendererTest.java
- close #108 
- depth 파싱 기능 구현
- image 파싱 기능 구현
- link 파싱 기능 구현
- 2 -> 4
=> [BE] 마크다운 Parser 기능 추가 구현

backend/src/main/java/org/donggle/backend/application/service/WritingService.java, backend/src/main/java/org/donggle/backend/application/service/request/WritingTitleRequest.java, backend/src/main/java/org/donggle/backend/config/InitData.java, backend/src/main/java/org/donggle/backend/domain/writing/Writing.java, backend/src/main/java/org/donggle/backend/ui/WritingController.java, backend/src/test/java/org/donggle/backend/application/service/WritingServiceTest.java
- close #128 
- 글 제목 수정 API 기능 구현
- 글 제목 수정 API 테스트 추가
- 로컬 및 테스트 환경에서 사용할 더미 데이터 추가
- 1 -> 0.5
=> [BE] feat: 글 제목 수정 기능 구현

.github/workflows/cicd-fe.yml
- close #148 
- 환경변수 생성 스크립트 수정
- 0.5
=> fix: `cicd-fe.yml` 환경변수파일`.env.development` 생성 스크립트 수정

backend/src/main/java/org/donggle/backend/domain/parser/notion/Annotations.java, backend/src/main/java/org/donggle/backend/domain/parser/notion/RichText.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/AnnotationsTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/BookmarkParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/CalloutParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/CodeBlockParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/DefaultBlockParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/HeadingParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/ImageParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/NotionBlockJsonBuilder.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/NotionBlockTypeTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/NotionParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/RichTextTest.java
- close #137 
- NotionParser테스트 추가
- 1
- 일단 Service는 충돌이 날 것 같아서 NotionParser만 테스트를 추가해둔 상황입니다.
=> [BE] test: NotionParser 테스트코드 추가

frontend/.storybook/preview-head.html, frontend/public/index.html, frontend/src/styles/GlobalStyle.tsx
- close #155 
- (0.5) + 0
- import vs cdn
`link` 가 병렬로 리소스를 다운로드 받기에 성능에 이점이 있습니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/link 보시면 아시겠지만 리소스 다운로드 최적화에 관한 여러 옵션을 제공해
기도 합니다
=> [FE] chore: 글로벌 폰트 추가

backend/src/main/java/org/donggle/backend/application/service/WritingService.java, backend/src/test/java/org/donggle/backend/application/service/tistory/TistoryApiServiceTest.java
- close #161 
- WritingService 내의 NotionApiService 제거
- TistoryApiServiceTest @Disabled 적용
- 0.1 -> 0.1
=> [BE] fix: git merge 충돌 오류 해결

backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownStyleParser.java, backend/src/main/java/org/donggle/backend/domain/parser/notion/BookmarkParser.java, backend/src/main/java/org/donggle/backend/domain/parser/notion/RichText.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlStyleRenderer.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlStyleType.java, backend/src/test/java/org/donggle/backend/domain/parser/MarkDownStyleParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/BookmarkParserTest.java, backend/src/test/java/org/donggle/backend/domain/parser/notion/DefaultBlockParserTest.java, backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlStyleRendererTest.java
- close #160 
- HTML LINK Render 구현
- 1
=> [BE] feat: StyleType Link HTML Render 기능 추가

.github/workflows/cicd-fe.yml, frontend/src/components/@common/Button/Button.tsx, frontend/src/pages/Layout/Layout.tsx, frontend/src/pages/WritingPage/WritingPage.tsx, frontend/src/pages/WritingTablePage/WritingTablePage.tsx
- close #163
- [transient-props](https://styled-components.com/docs/api#transient-props) 이용해 `Button` 컴포넌트 props 타입 수정
- cicd 스크립트 수정
- (1) + 0
-
=> [FE] fix: styled components props 네이밍 문제 해결, cicd 수정

backend/src/main/java/org/donggle/backend/application/service/WritingService.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlStyleRenderer.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlStyleType.java, backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlStyleRendererTest.java
- close #167 
- 렌더링에서 Style이 0,0 인덱스일 경우 렌더되는 문제 해결
- WritingService에서 notionUploade시에 title 저장 문제 해결
- 0
-
=> [BE] fix: WritingService 버그 픽스 및 Render 수정

backend/src/main/java/org/donggle/backend/application/service/request/CategoryAddRequest.java, backend/src/main/java/org/donggle/backend/application/service/request/PublishRequest.java, backend/src/main/java/org/donggle/backend/application/service/request/WritingModifyRequest.java, backend/src/main/java/org/donggle/backend/ui/CategoryController.java, backend/src/main/java/org/donggle/backend/ui/WritingController.java, backend/src/main/java/org/donggle/backend/ui/common/GlobalExceptionHandler.java
- close #175 
-  잘못된 요청이 왔을 때 에러를 처리해주는 기능
- 0
=> [BE] fix: 클라이언트 요청 오류에 대한 예외 처리 기능 추가

backend/build.gradle
- close #177
- Swegger의존성 추가
- 0.01
=> [BE] feat: Swagger 의존성 추가

frontend/src/components/@common/Input/Input.stories.tsx, frontend/src/components/@common/Input/Input.tsx, frontend/src/styles/theme.ts
- close #173 
- 3(+0)
- Input 컴포넌트 구현해봤습니다. 천천히 교체하면 좋을 것 같아요
=> [FE] feat: `Input` 컴포넌트 구현

backend/src/main/java/org/donggle/backend/ui/common/GlobalExceptionHandler.java
- close #180 
- HttpMediaTypeNotSupportedException 예외 핸들러 추가
- 0
=> [BE] fix: HttpMediaTypeNotSupportedException Handler 추가

.github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, backend/Dockerfile, docker-compose.yml
=> [BE] feat: PROD용 서버 설정 변경

frontend/src/components/FileUploadModal/FileUploadModal.tsx, frontend/src/components/FileUploadModal/useFileUploadModal.ts, frontend/src/components/WritingPropertySection/WritingPropertySection.tsx, frontend/webpack.common.js
=> [FE] feat: `WritingTableView`에서 글 추가 시 해당 카테고리로 추가되도록 구현

.github/workflows/cicd-fe-prod.yml, frontend/Dockerfile-prod, frontend/webpack.common.js, frontend/webpack.dev.js, frontend/webpack.prod.js
- close #197
- actions yml 파일 추가
- Dockerfile 추가
- 배포 용 웹팩 설정 추가 (`mode=production`으로 배포)
- (0.5) + 0
-
=> [FE] chore: 프론트엔드 배포서버 CI/CD 스크립트 작성, 웹팩 설정 추가

frontend/package.json, frontend/webpack.common.js
- close #201
- 배포 webpack 설정 변경
- 0
-
=> [FE] fix: 배포 webpack 설정 변경

frontend/src/components/@common/Spinner/Spinner.tsx, frontend/src/components/WritingViewer/WritingViewer.tsx, frontend/src/pages/Layout/Layout.tsx, frontend/src/styles/layoutStyle.ts
- close #191 
- (1) + 0
- 로딩 스타일은 추후 변경해도 좋을 것같아요~!
=> [FE] design: 전체 스타일 개선 및 스타일드 컴포넌트 버그 수정

frontend/src/components/Category/Category/Category.tsx, frontend/src/components/Category/CategorySection/CategorySection.tsx, frontend/src/components/Category/isValidCategoryName.ts, frontend/src/components/Category/useCategoryInput.ts
=> [FE] feat: 카테고리 제목 유효성 검사 로직 추가

frontend/public/index.html, frontend/src/components/@common/Accordion/AccordionTitle.tsx, frontend/src/components/@common/Modal/Modal.tsx, frontend/src/components/@common/TagInput/TagInput.tsx, frontend/src/components/Category/Category/Category.tsx, frontend/src/components/Category/CategorySection/CategorySection.tsx, frontend/src/components/Category/WritingList/WritingList.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/PublishingPropertySection/PublishingPropertySection.tsx, frontend/src/components/PublishingPropertySection/usePublishingPropertySection.ts, frontend/src/components/PublishingSection/PublishingSection.tsx, frontend/src/components/WritingPropertySection/WritingPropertySection.tsx, frontend/src/components/WritingSideBar/WritingSideBar.tsx, frontend/src/components/WritingTable/WritingTable.tsx, frontend/src/components/WritingViewer/WritingViewer.tsx, frontend/src/mocks/categoryContentsMock.ts, frontend/src/mocks/writingTableMock.ts, frontend/src/pages/Layout/Layout.tsx
- close #156
- 시각장애인을 위해 웹 접근성을 챙깁니다
- 
-
=> [FE] feat: 시각장애인을 위해 글 추가, 카테고리, 글 발행 웹 접근성 관련 코드 추가

frontend/src/components/Category/CategorySection/CategorySection.tsx, frontend/src/components/Category/WritingList/WritingList.tsx
- close #203 
- (0.5) + 0
- 스크롤의 위치가 매우 맘에 들지 않습니다. 추후에 수정이 필요해보입니다.
=> [FE] design: 카테고리 스타일 수정

frontend/src/components/WritingPropertySection/WritingPropertySection.tsx, frontend/src/components/WritingSideBar/WritingSideBar.stories.tsx, frontend/src/components/WritingSideBar/WritingSideBar.tsx, frontend/src/pages/Layout/Layout.tsx
- close #205
- 글 정보가 새로 reload 되지 않는 현상 수정 
- 0.3(+0)
-
=> [FE] fix: 글 정보가 새로 reload 되지 않는 현상 수정

.github/ISSUE_TEMPLATE/bug-template.yml
=> [All] chore: 버그 템플릿 추가

.github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, backend/src/main/java/org/donggle/backend/application/repository/MemberRepository.java, backend/src/main/java/org/donggle/backend/application/service/AuthService.java, backend/src/main/java/org/donggle/backend/application/service/MemberService.java, backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/KakaoOAuthService.java, backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/dto/KakaoAccountResponse.java, backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/dto/KakaoProfileResponse.java, backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/dto/KakaoTokenResponse.java, backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/dto/ProfileResponse.java, backend/src/main/java/org/donggle/backend/application/service/request/OAuthAccessTokenRequest.java, backend/src/main/java/org/donggle/backend/domain/member/Member.java, backend/src/main/java/org/donggle/backend/ui/KakaoOAuthController.java, backend/src/main/resources/application-prod.yaml, backend/src/main/resources/application.yaml, docker-compose.yml
- close #221 
- 카카오 OAuth 연동
- 회원가입 및 로그인 구현
- 4 -> 3
- `KAKAO_CLIENT_ID`, `KAKAO_CLIENT_SECRET` Git Actions Secret Key로 환경 변수 추가
=> [BE] feat: 카카오 OAuth 로그인 연동

.github/workflows/cicd-be-prod.yml, .github/workflows/cicd-be.yml, backend/src/main/resources/application.yaml
- close #230
- gradle test에 환경 변수 추가
- 0
=> [BE] chore: gradle test에 환경변수 추가

backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/KakaoOAuthService.java, backend/src/main/java/org/donggle/backend/application/service/request/OAuthAccessTokenRequest.java
- close #249 
- `oAuthAccessTokenRequest` 파라미터 네이밍 변경
- 1 -> 1
=> [BE] fix: `oAuthAccessTokenRequest` 파라미터 네이밍 변경

frontend/src/apis/writings.ts, frontend/src/components/@common/Input/Input.tsx, frontend/src/components/Category/WritingList/WritingList.tsx, frontend/src/components/FileUploadModal/useFileUploadModal.ts, frontend/src/components/WritingPropertySection/WritingPropertySection.tsx, frontend/src/components/WritingTable/WritingTable.stories.tsx, frontend/src/components/WritingTable/WritingTable.tsx, frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx, frontend/src/components/WritingViewer/WritingViewer.stories.tsx, frontend/src/components/WritingViewer/WritingViewer.tsx, frontend/src/hooks/useFileUpload.ts, frontend/src/hooks/usePageNavigate.ts, frontend/src/mocks/handlers/writing.ts, frontend/src/pages/WritingPage/WritingPage.tsx, frontend/src/pages/WritingTablePage/WritingTablePage.tsx, frontend/src/routes/Router.tsx, frontend/src/types/apis/writings.ts
- close #240
- close #209
- 2 -> 2
- 글 제목 수정하고 카테고리에 반영하기 위해서 글에도 categoryId를 넘겨줬어요.
- 글 페이지 path가 writings/:categoryId/:writingId 로 바꼈고 그걸로 인한 수정사항이 좀 많습니다.
- `WritingViewer` 쪽만 자세히 보면 될 것 같아요.
=> [FE] feat: 글 제목 수정 기능 구현, 파일 업로드 용량 제한

.github/workflows/build-fe-dev.yml, .github/workflows/build-fe-prod.yml
- close #286 
- `DOMAIN_URL` Actions yml에 추가
- 0
=> [FE] chore: `DOMAIN_URL` Actions yml에 추가

backend/src/main/java/org/donggle/backend/application/service/PublishService.java, backend/src/main/java/org/donggle/backend/domain/blog/BlogWriting.java, backend/src/main/java/org/donggle/backend/exception/business/WritingAlreadyPublishedException.java, backend/src/test/java/org/donggle/backend/application/service/PublishServiceTest.java
=> [BE] feat: 중복 발행 방지 기능 추가

backend/src/main/resources/logback-spring.xml
- close #291 
- 기존의 logback-spring.xml 설정으로 롤백
- 0.1 -> 0.2
-
=> [BE] hotfix: 로그백 설정 롤백

backend/src/main/java/org/donggle/backend/application/service/vendor/exception/VendorApiException.java, backend/src/main/java/org/donggle/backend/application/service/vendor/exception/VendorApiForbiddenException.java, backend/src/main/java/org/donggle/backend/application/service/vendor/exception/VendorApiInternalServerError.java, backend/src/main/java/org/donggle/backend/application/service/vendor/exception/VendorApiNotFoundException.java, backend/src/main/java/org/donggle/backend/application/service/vendor/exception/VendorApiRequestException.java, backend/src/main/java/org/donggle/backend/application/service/vendor/exception/VendorApiUnAuthorizedException.java, backend/src/main/java/org/donggle/backend/ui/common/GlobalExceptionHandler.java, backend/src/main/java/org/donggle/backend/ui/config/WebMvcConfig.java
- close #289
- exception handler에 추가
- 0.5 -> 0.5
=> [BE] feat: vendor에서 발생하는 예외 handler추가

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
=> [ALL] chore: 안쓰는 이미지 제거 명령어 추가

frontend/src/components/@common/Button/Button.tsx, frontend/src/components/Category/WritingList/WritingList.tsx, frontend/src/components/PublishingSection/PublishingSection.tsx, frontend/src/components/WritingPropertySection/WritingPropertySection.tsx, frontend/src/components/WritingViewer/WritingViewer.tsx, frontend/src/constants/blog.ts, frontend/src/constants/blog.tsx, frontend/src/pages/Layout/Layout.tsx, frontend/src/pages/WritingPage/WritingPage.tsx, frontend/src/pages/WritingTablePage/WritingTablePage.tsx, frontend/src/styles/layoutStyle.ts, frontend/src/styles/theme.ts
=> [FE] refactor: 전체적인 레이아웃 UI 개선

backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/KakaoOAuthService.java
- close #296 
- OAuth로그인 커스텀 에러 추가
- 1 -> 1
=> [BE] refactor: OAuth 로그인 과정 중 예외 처리 로직 추가

backend/src/main/resources/logback-spring.xml
- close #300 
- 로그백 롤링 경로 수정
- 0.1 -> 0.1
-
=> [BE] refactor: `logback-spring.xml` 롤링 경로 수정

backend/src/main/java/org/donggle/backend/application/repository/CategoryRepository.java, backend/src/main/java/org/donggle/backend/application/service/CategoryService.java, backend/src/main/java/org/donggle/backend/application/service/PublishService.java, backend/src/main/java/org/donggle/backend/application/service/WritingService.java, backend/src/main/java/org/donggle/backend/ui/AuthController.java, backend/src/main/java/org/donggle/backend/ui/KakaoOAuthController.java
- close #305 
- 사용자의 권한을 판별해주는 기능 구현
- 쿠키 시간 단위 변경
- 1 -> 1
=> [BE] feat: 사용자의 접근을 제어하는 기능 추가

backend/src/main/java/org/donggle/backend/application/service/WritingService.java, backend/src/test/java/org/donggle/backend/application/service/WritingServiceTest.java
- close #307 
- 서비스에서 `findById`를 `findWritingAndTrashedWriting`를 사용하도록 변경
- 0
=> [BE] feat: 휴지통의 글 및 글 정보도 찾아오는 기능 추가

docker-compose.yml
- close #311 
- docker-compose.yml에 볼륨 바인딩 추가
- 0
=> chore: nginx log 경로 바인딩

backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java, backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/KakaoOAuthService.java, backend/src/main/java/org/donggle/backend/ui/AuthController.java
- close #320 
-  로그아웃 HTTP 메서드 수정
- 0.1 -> 0.1
-
=> [BE] fix: logout HTTP 메서드를 POST로 수정

backend/src/main/java/org/donggle/backend/ui/MemberController.java, backend/src/main/java/org/donggle/backend/ui/response/MemberPageResponse.java
- close #322 
- API 명세에 맞는 이름으로 변경
=> [BE] fix: API 명세에 맞는 이름으로 변경

backend/src/main/java/org/donggle/backend/application/service/connection/notion/NotionConnectionService.java, backend/src/main/java/org/donggle/backend/application/service/connection/tistory/TistoryConnectionService.java, backend/src/main/java/org/donggle/backend/ui/ConnectionController.java, backend/src/main/java/org/donggle/backend/ui/KakaoOAuthController.java, backend/src/main/java/org/donggle/backend/ui/common/GlobalExceptionHandler.java, backend/src/main/java/org/donggle/backend/ui/config/WebMvcConfig.java
=> [BE] fix: redirect uri 만드는 부분 사용자 인증 제거

conf-dev/nginx.conf
- close #336 
- nginx설정 변경
- 1 -> 1
=> [BE] hotfix: swagger를 보기위한 nginx 설정파일 수정

backend/src/main/java/org/donggle/backend/application/service/connection/notion/NotionConnectionService.java, backend/src/main/java/org/donggle/backend/application/service/connection/notion/dto/NotionUserResponse.java, backend/src/main/java/org/donggle/backend/application/service/connection/tistory/TistoryConnectionService.java, backend/src/main/java/org/donggle/backend/application/service/connection/tistory/dto/TistoryAccessTokenResponse.java, backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/TistoryApiService.java
- close #334 
- 티스토리 및 노션 연동 오류 해결
- 0
=> [BE] fix: 연결 오류 해결

backend/src/main/java/org/donggle/backend/application/service/connection/notion/dto/NotionTokenResponse.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlRenderer.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlStyleRenderer.java, backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlRendererTest.java
- close #316 
-  리스트 랜더링 오류 해결
- 6시간
=> [BE] fix: 리스트 랜더링 오류 해결

backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlRenderer.java
- close #341 
- 리스트 랜더링 오류 로직 변경
- 0
-
=> [BE] fix: 리스트 랜더링 오류 로직 변경

frontend/src/apis/login.ts, frontend/src/components/ConnectionSection/ConnectionSection.tsx, frontend/src/components/ConnectionSection/useConnect.ts, frontend/src/components/Login/KakaoLoginButton.tsx, frontend/src/components/Profile/Profile.tsx, frontend/src/constants/apis/url.ts, frontend/src/constants/components/myPage.ts, frontend/src/constants/components/oauth.ts, frontend/src/constants/message.ts, frontend/src/mocks/handlers/login.ts, frontend/src/pages/ConnectionPage/ConnectionPage.tsx, frontend/src/pages/ConnectionPage/useStoreConnectionPlatforms.ts, frontend/src/pages/MyPage/MyPage.tsx, frontend/src/pages/OauthPage/OauthPage.tsx, frontend/src/pages/OauthPage/useLoginOauth.ts, frontend/src/routes/Router.tsx, frontend/src/types/apis/login.ts
=> [FE] fix: 마이페이지 수정

frontend/src/components/Category/Category/Category.tsx, frontend/src/components/Category/Header/Header.tsx, frontend/src/components/Category/isValidCategoryName.ts, frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx, frontend/src/utils/validators.ts
글 제목 검사는 추가한 것
- close #327 
- 유효성 검사 로직 분리
- 글 제목 변경 시 빈 제목으로 변경이 안되도록 수정
- 0.5
-
=> [FE] feat: 글 제목 변경 시 유효성 검사 로직 추가

backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java, backend/src/main/java/org/donggle/backend/application/service/CategoryService.java
- "status == trashed && categoryId == 현재 카테고리"인 글 목록의 카테고리를 기본 카테고리로 변경
- close #343 
-  카테고리 삭제 로직 오류 해결
- 1
-
=> [BE] fix: 카테고리 삭제 오류 해결

frontend/src/pages/OauthPage/useLoginOauth.ts
=> [FE] fix: accessToken 로컬 스토리지 저장 시 stringify 하는 로직 제거

.github/workflows/deploy-prod.yml, backend/build.gradle, backend/src/main/java/org/donggle/backend/application/service/AuthService.java
- close #349 
- 액션즈에서 배포용 티스토리 환경변수 추가하도록 변경
- aws 로그 의존성 build.gradle에서 제거
- 0
=> [BE] chore: 티스토리 배포용 앱 및 환경변수 추가

backend/src/main/java/org/donggle/backend/application/service/connection/medium/MediumConnectionService.java, backend/src/main/java/org/donggle/backend/application/service/vendor/exception/VendorInvalidTokenException.java
- close #351
- medium 연결 확인 로직 추가
- 1 -> 1
=> [BE] feat: medium 연결 됐는지 확인 로직 추가

backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlRenderer.java, backend/src/main/java/org/donggle/backend/domain/renderer/html/HtmlType.java, backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlRendererTest.java
- close #353 
- plain text 검증 로직 추가
- 1 -> 1
-
=> [BE] fix: plain text 검증 로직 추가

frontend/src/components/Category/List/useCategories.ts, frontend/src/components/FileUploadModal/useFileUploadModal.ts
=> [FE] feat:카테고리 선택되지 않았을 때 글 가져오기 시 기본 카테고리로 들어가는 기능 추가

.github/workflows/build-fe-dev.yml, .github/workflows/build-fe-prod.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, conf-dev/nginx.conf, conf-prod/nginx.conf, docker-compose.yml
- close #366 
- nginx에 https 적용을 위한 설정 변경 (dev.donggle.blog)
- 비밀일 필요 없는 시크릿 환경 변수들 var로 변경
- 0
- 이제 개발서버에 https://dev.donggle.blog 로 접속 가능합니다.
- 개발서버 주소 변경과 같이 환경변수들을 정리했습니다.
- OAuth를 개발서버에서 사용하기 위해 Redirect URL들을 각 API에 추가했습니다.
- 개발서버 https 적용을 이미 테스트해서 성공하였습니다.
=> [ALL] chore: 개발서버 https 통신 적용

frontend/src/constants/apis/url.ts
- close #379 
- 벡엔드 API 변경에 따른 auth API 수정
- 0.1 -> 0.1
-
=> [FE] refactor:  벡엔드 API 변경에 따른 auth API 수정

.github/workflows/build-be-dev.yml, .github/workflows/build-be-prod.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .gitmodules, backend/src/main/resources/application.yml, docker-compose.yml
=> [BE] chore: 백엔드 application.properties submodule로 관리

frontend/src/constants/components/oauth.ts
=> [FE] 카카오 리다이렉트 경로 수정

backend/src/main/java/org/donggle/backend/infrastructure/client/medium/MediumApiClient.java
- close #404
- 미디움 발행 요청 dto에 contentFormat 파라미터 추가
- 0
=> [BE] fix: 미디움 발행 요청에 contentFormat 파라미터 추가

backend/src/main/java/org/donggle/backend/application/repository/CategoryRepository.java, backend/src/main/java/org/donggle/backend/application/service/CategoryService.java
- close #419 
- 사용자별 이름 중복 검사
- 1
=> [BE] hotfix: 사용자 별로 카테고리 이름 중복검사 오류 수정

backend/src/main/java/org/donggle/backend/ui/common/WebMvcConfig.java
- close #430 
- AuthInterceptor "/auth/token/refresh/" 경로 제외
- 0
=> [BE] fix: AuthInterceptor "/auth/token/refresh" 경로 제외

backend/src/main/java/org/donggle/backend/application/service/auth/AuthService.java, backend/src/main/java/org/donggle/backend/application/service/trash/TrashService.java
- close #433 
- 로그인 오류 수정
- 0
-
=> [BE] fix: 로그인 오류 수정

backend/src/main/java/org/donggle/backend/application/service/auth/AuthService.java, backend/src/main/java/org/donggle/backend/config/InitLocalAndTestData.java, backend/src/main/java/org/donggle/backend/domain/member/Member.java, backend/src/main/java/org/donggle/backend/infrastructure/file/S3UploadClient.java, backend/src/main/java/org/donggle/backend/infrastructure/oauth/kakao/dto/response/UserInfo.java, backend/src/test/java/org/donggle/backend/application/service/MemberServiceTest.java, backend/src/test/java/org/donggle/backend/domain/writing/BlockTest.java
- close #448
- member 생성자 초기화 오류 및 s3 컴플릭트 해결
- 0
=> [BE] fix:  커플릭트 해결

backend/src/main/java/org/donggle/backend/ui/response/PublishedDetailResponse.java
- close #459
- `url` -> `publishedUrl` 필드명 변경
- 0
=> [BE] fix: `url` -> `publishedUrl` 필드명 변경

backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClient.java, backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/dto/request/TistoryPublishRequest.java
- close #457 
- String -> LocalDateTime에서 String -> Date로 변경
- Date -> Instant(unix timestamp)로 변경 로직 추가
- tistory에 요청 보내는 published 파라미터 자료형 long으로 변경
- 0
=> [BE] fix: 티스토리 예약 기능 오류 수정

frontend/src/components/@common/Pagination/Pagination.tsx, frontend/src/components/HomeTable/HomeTable.tsx, frontend/src/components/HomeTable/useHomeTable.ts, frontend/src/mocks/homeWritingMock.ts
=> [FE] fix: `HomeTable` 페이지 인덱스 이슈 수정

backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
- close #478 
- rebase하며 지워진 로직 복구
- 0.1 -> 0.1
-
=> [BE] fix: rebase하며 지워진 로직 복구

backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClient.java
=> [BE] fix: 티스토리 카테고리 조회 로직 오류 수정

frontend/package.json, frontend/src/apis/category.ts, frontend/src/apis/fetch.ts, frontend/src/apis/login.ts, frontend/src/apis/member.ts, frontend/src/apis/trash.ts, frontend/src/apis/writings.ts, frontend/src/mocks/handlers.ts, frontend/src/mocks/handlers/auth.ts, frontend/src/mocks/handlers/error.ts, frontend/src/mocks/handlers/login.ts, frontend/src/mocks/handlers/writing.ts, frontend/src/types/apis/login.ts, frontend/src/utils/apis/HttpError.ts, frontend/yarn.lock
=> [FE] feat: `accessToken` 만료 시 재발급하는 기능

frontend/public/index.html
- close #481
- 구글 애널리틱스 추가
- 0.5 -> 0.5
- 지금은 첫 방문자 통계만 잡히는데 나중에 페이지별로 통계를 내고싶으면 react-ga 라이브러리를 사용하면 될 것 같습니다
=> [FE] chore: 구글 애널리틱스 추가

frontend/src/mocks/handlers/writing.ts
- 이슈 x
- 단순히 import 문이 없어서 생긴 에러 핫픽스
- 0
-
=> [FE] hotfix: import 에러 수정

frontend/src/components/@common/Modal/Modal.tsx, frontend/src/components/Header/Header.tsx
- close #528
- 0.1 -> 0.1
- 모달 닫기 버튼에 추가하는 김에 헤더 아이콘 들에도 호버 효과 추가했습니다
=> [FE] refactor: 아이콘 버튼에 호버 시 효과 추가

frontend/src/components/Category/Category/Category.tsx, frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx
=> [FE] refactor: 글, 카테고리 제목 수정 시 기존 제목이 유지되도록 수정

frontend/src/components/FileUploadModal/FileUploadModal.tsx
- close #529
이제 글 가져오기 모달에서 url 입력 후 엔터쳐서 노션 글 가져올 수 있습니다🙂
- 0.5
-
=> [FE] feat: 노션 링크 입력 `input`창 엔터쳐서 글 가져오는 기능 추가

frontend/src/components/HomeTable/HomeTable.tsx, frontend/src/components/TrashCanTable/TrashCanTable.tsx, frontend/src/components/WritingTable/WritingTable.tsx
- close #524 
- 0.5 -> 0.5
https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/a27e1dd3-0ff1-40e0-b18c-84ecda27602b
- 테이블에 비슷한 로직이 많아서 추상화하는 것도 괜찮을 것같아요.
- 현재 휴지통에서 체크박스 테이블 부분이 조금 애매해요. 아래 영상 참고하시면 될 것같아요.
https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/9a8607df-2457-467b-9f9e-56d95081d11e
=> [FE] design: 글 목록 호버 시 효과 변경

frontend/src/apis/member.ts, frontend/src/mocks/handlers/member.ts
- close #543
- 회원 탈퇴 HTTP 상태 코드 변경(POST -> DELETE)
- 0.1 -> 0.1
-
=> [FE] refactor: 회원 탈퇴 HTTP 상태 코드 변경

backend/src/test/java/org/donggle/backend/domain/renderer/html/HtmlRendererTest.java
=> [BE] fix: 리스트 테스트 오류 수정

.github/workflows/build-be-dev.yml, .github/workflows/build-be-prod.yml, docker-compose.yml
- close #554 
- Actions에서 빌드할때 이미지 분리
- 도커 컴포즈에서 별도의 이미지 
- 0
=> [BE] chore: 백엔드 컨테이너 이미지 분리

backend/src/test/java/org/donggle/backend/application/service/concurrent/NoConcurrentAccessAspectTest.java
- NoConcurrentAccessAspectTest Disabled추가
- 0
=> [BE] refactor: NoConcurrentAccessAspectTest Disabled추가

backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/dto/response/TistoryGetWritingResponseWrapper.java, backend/src/test/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClientTest.java
=> [BE] fix: 티스토리 발행 후 응답에서 시간 변환 메서드 롤백

.github/workflows/build-be-dev.yml, .github/workflows/build-be-prod.yml, backend/Dockerfile, backend/Dockerfile-dev, backend/Dockerfile-prod, compose-blue.yml, compose-green.yml
=> [BE] chore: 개발서버에 datadog을 위한 agent 설정

backend/src/main/java/org/donggle/backend/application/service/publish/PublishFacadeService.java
- close #598 
-  [x] 랜더링 전 List에 대해 detach() 추가
- 0
-
=> [BE] fix: 티스토리 이미지 랜더링 오류 수정

backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClient.java, backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryConnectionClient.java, backend/src/main/java/org/donggle/backend/ui/BlogController.java, backend/src/main/java/org/donggle/backend/ui/ConnectionController.java, backend/src/main/java/org/donggle/backend/ui/PublishController.java, backend/src/test/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClientTest.java, backend/src/test/java/org/donggle/backend/infrastructure/client/tistory/TistoryConnectionClientTest.java, backend/src/test/java/org/donggle/backend/ui/BlogControllerTest.java, backend/src/test/java/org/donggle/backend/ui/ConnectionControllerTest.java, backend/src/test/java/org/donggle/backend/ui/ControllerTest.java, backend/src/test/java/org/donggle/backend/ui/PublishControllerTest.java
- close #614 
- Controller Mapping 주석 처리
- TistoryAPIClient 주석 처리
- TistoryConnectionClient 주석 처리
- 테스트 주석 처리
- 테스트 확인 완료
- 코드 지우기 대신 주석 처리
=> fix: Tistory API 연결 종료
