woowacourse-teams/2023-dong-gle

frontend/src/apis/writings.ts
frontend/src/hooks/@common/useGetQuery.ts
frontend/src/hooks/@common/useMutation.ts
frontend/src/hooks/@common/useMutationQuery.ts
frontend/src/hooks/useFileUpload.ts
frontend/src/index.tsx
frontend/src/types/apis/writings.ts
frontend/webpack.config.js

- close #15
- 2(+0)
- 개발자 도구에 뜨는 에러들을 해결을 위해서 설정을 추가하였습니다.
- 웹팩에 `devtool: sourcemap` 지정을 하지 않아서 sourcemap load를 할 수 없다고 뜨는 에러 해결
- msw의 핸들러에 추가되어 있지 않은 요청 처리는 msw를 거치지 않고 그대로 처리하는 옵션 추가(`index.tsx`)
- `addWriting` API body 데이터 수정
- `'Content-Type': 'multipart/form-data'`으로 해놔서 `json`형태가 아니라 `FormData`를 그대로 넘겨야해서 수정
- `addWritingRequest` Type도 같이 수정
- `useMutation` 훅
- 훅 이름 변경
- query훅 `loading` -> `isLoading`으로 변경
- 글 생성 API 연결
- 파일 타입 검사하는 부분은 삭제하였습니다. -> 서버에서 검사하기도 하고, 검사하는 로직이 조금 까다로움.
- `useMutation` 훅을 사용하여 구현
- mutateQuery에 body 데이터를 넣는 것이 필요해서 useMutation 훅을 약간 리팩토링(5af02520954d10f03f5f5b17477a4d29c220a58e)

[FE] feat: 글 생성 API 연결

---

frontend/.storybook/main.ts
frontend/.storybook/preview.tsx
frontend/package.json
frontend/src/apis/writings.ts
frontend/src/components/WritingViewer/WritingViewer.stories.tsx
frontend/src/components/WritingViewer/WritingViewer.tsx
frontend/src/constants/apis/url.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/handlers/writing.ts
frontend/src/mocks/writingContentMock.ts
frontend/yarn.lock

- close #35
- close #36
- close #59
- `WritingViewer` 컴포넌트 추가
-  <img width="686" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/7c667249-def4-452a-9fad-f74e222b8723">
- <img width="550" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/f7543b13-8dd3-445a-b96a-b2b57387a26a">
- html sanitize를 위해 `dompurify` 라이브러리 설치
- `WritingViewer` 스토리 추가
- 글 조회 api를(GET `/wrtings/writingId`) 연결
- 글 조회 api msw mocking
- `msw-storybook-addon` 라이브러리 설치
- storybook에 msw 설정
- 0
- `WritingViewer` 컴포넌트 내부 스타일링은 규모가 커보여서 따로 이슈 파서 진행하겠습니다.
- 트리플 프로그래밍으로 진행하는 것이 좋아보여요
- `dangerouslySetInnerHTML`로 html을 바로 주입하면 `XSS` 등의 위협이 있기 때문에 `DOMPurify` 라이브러리를 이용해 html sanitize 하여 주입합니다.
- 추후 `WritingViewer` 스토리에 msw 관련 코드 리팩터링은 `mocks/handlers` 리팩터링과 함께 …

[FE] feat: `WritingViewer` 컴포넌트 구현, 글 조회 api 연결, storybook msw 설정

---

.github/workflows/cicd-fe.yml
frontend/.gitignore
frontend/Dockerfile
frontend/package.json
frontend/src/constants/apis/url.ts
frontend/src/index.tsx
frontend/src/types/global.d.ts
frontend/webpack.common.js
frontend/webpack.dev.js
frontend/yarn.lock

- close #146 
- 환경변수 관련 라이브러리 `cross-env`, `dotenv-webpack` 설치
- 환경변수 github secrets에 추가 (`BASE_URL_DEVELOPMENT`, `BASE_URL_PRODUCTION`)
- <img width="1068" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/640e0e9d-86e2-4fd9-a9b8-48b6e5d87fb4">
- 프론트엔드 cicd yml 파일(github actions)에서 환경변수 파일 만들어서 주입
- 프론트엔드 Dockerfile 빌드 명령어 변경
- 로컬에 `.env.development`, `.env.production` 추가 (공유 예정)
- (6) + 3
현재 cicd yml과 Dockerfile은 dev 서버 기준으로 작성되어 있습니다.
추후 production 환경을 구성할 때,  cicd yml과 Dockerfile을 따로 만들어야합니다.

[FE] chore: 프론트엔드 환경변수(`.env`, `cross-env`) 설정

---

frontend/src/components/WritingPropertySection/WritingPropertySection.stories.tsx
frontend/src/components/WritingPropertySection/WritingPropertySection.tsx
frontend/src/mocks/handlers/writing.ts
frontend/src/types/apis/writings.ts
frontend/src/utils/date.ts

- close #133
- 3(+1)
- 글 정보 섹션을 구현했어요. 폰트 적용도 해야할 듯 하네요 기본 폰트가..
머지되지 않은 PR들 다 머지되면 마지막으로 사이드바 할 것
- Tab에 글 정보 섹션 추가
- 글 발행 완료 시 글 정보 섹션으로 이동

[FE] feat: 글 정보 섹션 `WritingPropertySection` 구현

---

backend/src/main/java/org/donggle/backend/application/service/CategoryService.java
backend/src/main/java/org/donggle/backend/application/service/WritingService.java
backend/src/main/java/org/donggle/backend/domain/writing/content/RawText.java
backend/src/main/resources/application-prod.yaml
backend/src/test/java/org/donggle/backend/application/service/CategoryServiceTest.java

- close #179 
-  카테고리 생성 후 목록 조회 시, 글 목록이 비어있을 때 빈 배열을 전송하도록 수정
-  카테고리 삭제 수정
- 삭제된 카테고리 내의 글이 비어있을 때, 기본 카테고리로 글을 이동시키는 로직을 적용하지 않도록
- 카테고리 삭제시 기본 카테고리가 비어있을 때 순환 참조가 일어난다.
- 글이 있는 카테고리를 삭제시, 기본 카테고리에서 순환 참조가 일어난다.
-  production 환경의 JPA 테이블 생성 전략 수정
-  RawText에 columnDefinition 조건 추가
- 2 -> 1

[BE] fix: 카테고리 오류 수정 및 개발 환경 수정

---

.github/workflows/cicd-fe-prod.yml
.github/workflows/cicd-fe.yml
docker-compose.yml

[FE] chore: frontend 브랜치별 docker 이미지 분리

---

frontend/src/assets/icons/index.ts
frontend/src/assets/icons/plus.svg
frontend/src/components/Category/Category/Category.tsx
frontend/src/components/Category/CategorySection/CategorySection.tsx
frontend/src/components/Category/useCategoryInput.ts

[FE] fix: category icon click 버그 수정

---

backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/KakaoOAuthService.java
backend/src/main/java/org/donggle/backend/application/service/oauth/notion/NotionOAuthService.java
backend/src/main/java/org/donggle/backend/application/service/oauth/tistory/TistoryOAuthService.java
backend/src/main/java/org/donggle/backend/application/service/request/OAuthAccessTokenRequest.java

- close #249 
- NotionOAuthService `oAuthAccessTokenRequest` 파라미터 네이밍 변경
- TistoryOAuthService `oAuthAccessTokenRequest` 파라미터 네이밍 변경
- 0.1

fix: `oAuthAccessTokenRequest` 파라미터 네이밍 변경

---

.github/draft-release.yml
.github/workflows/semantic-versioning.yml
frontend/package.json

- close #238
- 4 -> 6
**main으로 pr날릴 때** label(`major`, `minor`, `patch`)에 따라서 tag의 버전이 업데이트 됩니다. 
또한 그 태그에 해당하는 release note가 초안으로 생성되며 작성완료는 직접 해줘야 합니다.
frontend/package.json 에 있는 version 역시 같이 업데이트 되며 이 변경사항은 main으로 바로 push 됩니다.
이 커밋을 통해서 어디까지가 어떤 버전인지 확인 가능합니다.
그리고 이 PR이 main으로 merge되야 다음 main에 머지될 때부터 반영될 것 같은데 어떻게 할까요?

[All] chore: 시멘틱 버저닝

---

backend/src/main/java/org/donggle/backend/application/service/PublishService.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/TistoryApiService.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/TistoryBlogInfoResponse.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/TistoryBlogInfoResponseWrapper.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/TistoryBlogResponse.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/TistoryBlogStatsResponse.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/request/TistoryPublishRequest.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/request/TistoryPublishWritingDataRequest.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/response/TistoryGetWritingResponse.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/response/TistoryGetWritingResponseWrapper.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/response/TistoryItemResponse.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/response/TistoryPublishStatusResponse.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/response/TistoryPublishWritingResponse.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/response/TistoryPublishWritingResponseWrapper.java
backend/src/main/java/org/donggle/backend/application/service/vendor/tistory/dto/response/TistoryResponse.java
backend/src/test/java/org/donggle/backend/application/service/tistory/TistoryApiServiceTest.java

- close #265 
- Tistory API Response DTO 정리
- 글 발행시 Tistory 블로그 이름을 조회하여 찾은뒤 발행할 수 있도록 변경
- 이름 찾는 테스트 추가(Disabled)
- 0
- 티스토리 블로그 발행을 위해서는 블로그 이름이 필요합니다.({name}.tistory.com)의 이름이 필요합니다.
- 전에는 티스토리 블로그 이름을 DB에 직접 주입하여 글을 발행하였습니다.
- 이번 기능으로 access token을 통해 블로그 이름을 찾아올 수 있습니다.
- Member Credential쪽 기능이 완성되면 블로그 이름을 한 번 찾고 DB에 영속화하는 형식으로 구현해나갈 수 있을 것 같습니다.

[BE] feat: 티스토리 블로그 이름 가져오는 기능 구현

---

backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
backend/src/main/java/org/donggle/backend/application/service/TrashService.java
backend/src/main/java/org/donggle/backend/application/service/request/DeleteWritingsRequest.java
backend/src/main/java/org/donggle/backend/application/service/request/RestoreWritingsRequest.java
backend/src/main/java/org/donggle/backend/domain/writing/Writing.java
backend/src/main/java/org/donggle/backend/domain/writing/WritingStatus.java
backend/src/main/java/org/donggle/backend/exception/notfound/DeleteWritingNotFoundException.java
backend/src/main/java/org/donggle/backend/exception/notfound/RestoreWritingNotFoundException.java
backend/src/main/java/org/donggle/backend/exception/notfound/WritingNotFoundException.java
backend/src/main/java/org/donggle/backend/ui/TrashController.java
backend/src/main/java/org/donggle/backend/ui/response/TrashResponse.java
backend/src/main/java/org/donggle/backend/ui/response/TrashedWritingResponse.java
backend/src/test/java/org/donggle/backend/application/service/TrashServiceTest.java

- close #280 
- 1
- Writing에 `@SQLDelete(sql = "UPDATE writing SET status = 'DELETED' WHERE id = ?")`로 `repository.delete`로 엔티티 삭제시 status를 DELETED로 변경하도록 하였습니다.
- Writing에 `@Where(clause = "status = 'ACTIVE'")`를 추가하여 기존 repository 메서드 변경 없이 사용할 수 있도록 하였습니다. 예를 들어 findById로 writing을 찾을시 status=ACTIVE인 writing만 찾아올 것입니다.
- status=TRASHED,DELETED일 경우에는 @Query에 nativequery를 사용하여 찾아오도록 하였습니다.

[BE] feat: 글 삭제 및 휴지통 API 구현

---

frontend/src/App.tsx
frontend/src/apis/fetch.ts
frontend/src/components/@common/Modal/Modal.tsx
frontend/src/components/Category/Category/Category.tsx
frontend/src/components/ErrorBoundary/ErrorBoundary.tsx
frontend/src/components/FileUploadModal/useFileUploadModal.ts
frontend/src/components/PublishingPropertySection/usePublishingPropertySection.ts
frontend/src/hooks/useFileUpload.ts
frontend/src/mocks/handlers/category.ts
frontend/src/mocks/handlers/writing.ts
frontend/src/pages/ErrorPage/ErrorPage.tsx
frontend/src/routes/Router.tsx
frontend/src/utils/apis/HttpError.ts
frontend/src/utils/error.ts

- close #262
- `App`의 ErrorBoundary는 중간에 handling되지 않은 httpError를 잡아서 `ErrorPage`를 렌더링합니다
- 3,4,500대 상태코드 error는 커스텀 Error인 `httpError`로 감싸져서 throw됩니다.
- 상태코드 에러가 아닌 에러들은 try catch로 감싸서 alert이나 toast로 보여줍니다.
- 추후 alert과 toast를 보여주는 기준을 정해야할 것 같습니다. 
- 각 throw 하는 부분은 validate~ 함수로 리팩터링 하면 좋을 것 같습니다.
- 10 + 6
-

[FE] feat: 전체적인 에러처리 코드 추가

---

backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java

- close #304 
- JPA 메서드 Query의 `Writing` -> `writing`으로 키워드 변경
- 0

[BE] fix: query의 `Writing` -> `writing`으로 키워드 변경

---

backend/src/main/java/org/donggle/backend/application/service/MemberService.java
backend/src/main/java/org/donggle/backend/application/service/PublishService.java
backend/src/main/java/org/donggle/backend/application/service/WritingService.java
backend/src/main/java/org/donggle/backend/domain/member/MemberCredentials.java
backend/src/main/java/org/donggle/backend/exception/business/MediumNotConnectedException.java
backend/src/main/java/org/donggle/backend/exception/business/NotionNotConnectedException.java
backend/src/main/java/org/donggle/backend/exception/business/TistoryNotConnectedException.java
backend/src/main/java/org/donggle/backend/ui/AuthController.java
backend/src/main/java/org/donggle/backend/ui/MemberController.java
backend/src/main/java/org/donggle/backend/ui/config/WebMvcConfig.java
backend/src/main/java/org/donggle/backend/ui/response/MediumConnectionResponse.java
backend/src/main/java/org/donggle/backend/ui/response/MemberPageResponse.java
backend/src/main/java/org/donggle/backend/ui/response/NotionConnectionResponse.java
backend/src/main/java/org/donggle/backend/ui/response/TistoryConnectionResponse.java
backend/src/main/java/org/donggle/backend/ui/response/WritingResponse.java
backend/src/test/java/org/donggle/backend/application/service/MemberServiceTest.java

[BE] feat: MemberPage 조회 API 구현

---

backend/src/main/java/org/donggle/backend/application/service/PublishService.java

- close #314 
- PublishService의 findWriting에서 writingId와 memberId를 반대로 입력한 부분 수정
- 0.1 ->0.01

[BE] fix: findWriting 버그 수정

---

frontend/src/App.tsx
frontend/src/components/FileUploadModal/useFileUploadModal.ts
frontend/src/components/TrashCan/DeletedWritingList.tsx
frontend/src/components/TrashCanTable/TrashCanTable.tsx
frontend/src/components/WritingSideBar/WritingSideBar.stories.tsx
frontend/src/components/WritingSideBar/WritingSideBar.tsx
frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx
frontend/src/components/WritingViewer/WritingViewer.tsx
frontend/src/hooks/usePageNavigate.ts
frontend/src/pages/Layout/Layout.tsx
frontend/src/pages/MyPage/MyPage.tsx
frontend/src/pages/WritingPage/WritingPage.tsx

- close #328
- development mode일 때만 ReactQueryDevtools 렌더링 되도록 수정
- 마이페이지 로딩 스피너 위치 중앙으로 이동
- 글 추가 실패 시 에러 토스트 출력
- `WritingViewer`의 글이 바뀌면 `WritingSideBar` 의 `currentTab`을 글 정보로 변경
- 휴지통에 있는 글을 볼 때 글 제목변경, 발행 안되게 수정
- 글을 보는 페이지로 이동하는 라우팅 로직인 goWritingPage을 할 때, 삭제된 글인지 여부를 location.state로 넣어줍니다. WritingPage에서는 location.state를 꺼내서 글 제목 수정을 막기 위해 WritingViewer에 prop으로 넣어주고, 사이드바 발행탭을 없애기위해 setActiveWritingInfo에 넣어 호출합니다. 
- 오른쪽 글 정보 사이드바: Layout 에 있는 PageContext의 setActiveWritingId를 setActiveWritingInfo 객체로 수정하여 객체 내부에는 기존 setActiveWritingId와 삭제된 글인지 여부인 isDeleted가 정의됩니다. isDeleted를 WritingSideBar prop으로 넣어서 오른쪽 사이드 바 글 정보 섹션의 조건부 렌더링을 수행합니다.
- 글 제목 수정: goWritingPage을 할 때 넣어주는 isDeletedWriting(location.state)값을 WritingPage에서 꺼내기 때문에, 바로WritingViewer의 prop으로 isDeletedWriting을 넣어주어 조건부 렌더링을 …

[FE] feat: 휴지통에 있는 글을 볼 때 글 제목변경, 발행 안되게 수정

---

frontend/src/components/Category/useCategoryMutation.ts

- close #360 
- 카테고리 삭제 시 카테고리 내부 글들을(`writingsInCategory`) invalidate
- 0.1
-

[FE] fix: 글이 있는 카테고리 삭제 시 왼쪽 사이드바에서 글들이 기본 카테고리로 옮겨진 것을 볼 수 없는 버그 수정

---

backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
backend/src/main/java/org/donggle/backend/application/service/CategoryService.java
backend/src/test/java/org/donggle/backend/application/service/CategoryServiceTest.java

- close #359 
- 카테고리를 변경할때, 영구삭제된 글들도 카테고리를 기본 카테고리로 변경하도록 수정
- 
- 테스트 코드 추가해서 돌아가는 것 확인
- 프로덕션환경에서 수정된 쿼리와 똑같은 쿼리를 실행시켜서 카테고리가 성공적으로 삭제되는 것을 확인

[BE] fix: 영구삭제된 글들도 카테고리를 변경해주도록 메서드 변경

---

frontend/package.json
frontend/webpack.common.js
frontend/yarn.lock

- close #381 
- `bundleAnalyzerPlugin` 설치 및 설정
- 0.2 + (0.1)
`BundleAnalyzerPlugin`은 웹 서버로 실행하거나 빌드할 때 기본적으로 함께 실행되므로, 옵션을 통해 매번 열리지 않게 했습니다.
대신 script를 추가하여 원할 때 플러그인을 이용할 수 있도록 설정했어요.
```js
// webpack.config.js
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
module.exports = {
...
plugins: [
...
new BundleAnalyzerPlugin({
analyzerMode: 'static', // 분석 결과 html 파일을 dist에 저장
openAnalyzer: false, // 웹 서버로 실행하거나 빌드할 때 Analyzer를 열지않음
generateStatsFile: true, // 분석 파일을 저장
statsFilename: 'bundle-report.json', // 분석 파일(json)이름 지정
}),
],
...
};
```
```
yarn analyze
```

[FE] chore: 번들 사이즈 최적화를 위해 `bundleAnalyzerPlugin` 설치 및 설정

---

frontend/src/apis/member.ts
frontend/src/components/Modal/DeleteAccountModal.tsx/DeleteAccountModal.tsx
frontend/src/components/Profile/Profile.tsx
frontend/src/hooks/queries/member/useMemberDelete.ts
frontend/src/mocks/handlers/member.ts

- close #388
- 0.5 -> 2
- 탈퇴 시 한번 더 확인할 수 있는 모달을 추가했습니다.
- 탈퇴 완료 시 accessToken을 지우고 introduce 페이지로 리다이렉트 시켰습니다.

[FE] feat: 회원 탈퇴 기능 구현

---

backend/src/main/java/org/donggle/backend/application/service/MemberService.java
backend/src/main/java/org/donggle/backend/domain/member/Member.java
backend/src/main/java/org/donggle/backend/ui/MemberController.java
backend/src/test/java/org/donggle/backend/application/service/MemberServiceTest.java

- close #407 
- 회원 탈퇴 컬럼 추가
- 소프트 딜리트 구현
- 스케줄 작동 테스트
- 해당 회원의 정보 삭제 로직 구현
- 3
애플리케이션 상에서 회원 탈퇴는 소프트 딜리트로 구현하였습니다. 이를 위해 isDeleted와 deletedAt 컬럼을 추가하였고, 실제 데이터베이스에서 회원 정보를 삭제하는 것은 ec2에서 crontab 스케줄러를 사용하여 구현하였습니다. 매일 새벽 3시에 데이터베이스에서 탈퇴한지 30일이 지난 사용자들의 정보를 삭제해주도록 설정하였습니다. 이에 대한 자세한 내용은 블로그에 작성하겠습니다.
스프링 애플리케이션이 아닌 ec2에서 직접 스케줄러와 sql 스크립트를 작동시킨 이유는, 굳이 애플리케이션의 연산 자원을 사용하기보다 많은 데이터를 한 번에 처리하는 것은 독립적인 스크립트로 작성하는 것이 좋다고 판단했기 때문입니다.

[BE] feat: 회원 탈퇴 기능 구현

---

backend/src/main/java/org/donggle/backend/application/client/LoginClient.java
backend/src/main/java/org/donggle/backend/application/repository/MemberInfo.java
backend/src/main/java/org/donggle/backend/application/repository/MemberRepository.java
backend/src/main/java/org/donggle/backend/application/repository/dto/MemberInfo.java
backend/src/main/java/org/donggle/backend/application/service/auth/AuthFacadeService.java
backend/src/main/java/org/donggle/backend/application/service/auth/AuthService.java
backend/src/main/java/org/donggle/backend/application/service/auth/LoginClients.java
backend/src/main/java/org/donggle/backend/domain/member/Member.java
backend/src/main/java/org/donggle/backend/infrastructure/oauth/kakao/KakaoLoginClient.java
backend/src/main/java/org/donggle/backend/infrastructure/oauth/kakao/KakaoLoginUserInfoClient.java
backend/src/main/java/org/donggle/backend/infrastructure/oauth/kakao/dto/response/KakaoProfileResponse.java
backend/src/main/java/org/donggle/backend/infrastructure/oauth/kakao/dto/response/SocialUserInfo.java

- close #421
-  memberAuth DTO도입 후 로그인 로직에 적용
- 1

[BE] refactor: 회원조회할때 커버링 인덱스가 적용되도록 수정

---

backend/src/main/java/org/donggle/backend/application/repository/BlogWritingRepository.java
backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
backend/src/main/java/org/donggle/backend/application/service/blog/PublishService.java
backend/src/main/java/org/donggle/backend/application/service/category/CategoryService.java
backend/src/main/java/org/donggle/backend/application/service/writing/WritingFacadeService.java
backend/src/main/java/org/donggle/backend/application/service/writing/WritingService.java
backend/src/test/java/org/donggle/backend/application/NoConcurrentAccessAspectTest.java

- close #425
- 글을 가져올때 글의 블럭마다 select쿼리를 날리는 로직 in절 추가
- 블로그 발행 여부 쿼리 JOIN FETCH추가
- 2

[BE] refactor: 여러번 쿼리나가는 글 가져오기, 글 발행정보 쿼리 수정

---

backend/src/main/java/org/donggle/backend/application/client/BlogClient.java
backend/src/main/java/org/donggle/backend/application/service/blog/PublishFacadeService.java
backend/src/main/java/org/donggle/backend/application/service/request/PublishRequest.java
backend/src/main/java/org/donggle/backend/domain/blog/BlogClients.java
backend/src/main/java/org/donggle/backend/domain/blog/PublishStatus.java
backend/src/main/java/org/donggle/backend/exception/business/InvalidPublishRequestException.java
backend/src/main/java/org/donggle/backend/infrastructure/client/medium/MediumApiClient.java
backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClient.java
backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryConnectionClient.java
backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/dto/request/TistoryPublishRequest.java
backend/src/main/java/org/donggle/backend/ui/PublishController.java
backend/src/main/java/org/donggle/backend/ui/WritingController.java
backend/src/test/java/org/donggle/backend/application/service/PublishServiceTest.java

- close #422 
- 글 발행 API 분리 (PublishController)
- 티스토리 발행하기 API 수정
- 미디움 발행하기 API 수정
- +2
- API 테스트 결과 변경된 API로 제대로 발행되는 것을 확인했습니다.
- 티스토리 발행 선택 정보 중 `publishTime`의 DateTime 형식이 티스토리에서 요구하는 형식과 다른지 예약 기능이 제대로 되지 않아서 해당 부분은 조금 더 찾아봐야 할 것 같습니다 🥲
1. PublishRequest 내부 예외 처리
- 현재 `PublishController`에서 `PublishRequest`로 요청을 받아 서비스로 전달하고 있습니다. 이 때 각 api에 맞는 스펙으로 예외 검증을 하는 로직이 `PublishRequest` 내부에 있습니다.
- 이렇게 구현하게 된 이유는 `publishService`에서부터 각 `ClientApi`까지 추상화되어 있어 블로그에 맞는 예외를 체크하려면 각 `ClientApi`까지 들어가야 합니다. 하지만 `publishService`에서 랜더링을 하고 있어서 랜더링이 시작되기 전에 예외를 던져줘서 불필요한 시간 낭비를 줄이고 싶었습니다.
- 해당 검증 로직의 위치가 괜찮을지 얘기를 나눠보고 싶습니다.
2. 해당 API 의 예외 처리 로직..
- 현재 `PublishRequest`와 `TistoryClientApi`에서 요청으로 들어온 값에 대한 검증을 한 뒤 `IllegalArgumentException`을 던지고 있습니다. 커스텀 예외처리를 해주고 싶은데 해당 검증이 비즈니스로직인가.. 에 대한 의문에 빠져 …

[BE] feat: 미디움, 티스토리 발행 시 선택 정보 추가 기능 구현

---

backend/src/main/java/org/donggle/backend/application/service/category/CategoryService.java
backend/src/main/java/org/donggle/backend/application/service/writing/WritingService.java
backend/src/main/java/org/donggle/backend/domain/writing/Writing.java
backend/src/main/java/org/donggle/backend/exception/business/InvalidBasicCategoryException.java
backend/src/test/java/org/donggle/backend/application/service/CategoryServiceTest.java
backend/src/test/java/org/donggle/backend/application/service/ModifyCategoryOrderTest.java
backend/src/test/java/org/donggle/backend/application/service/ModifyWritingOrderTest.java

- close #454
- 카테고리의 순서 이동 수정
- 글의 순서 이동 수정
- 테스트 케이스 추가
- 2 -> 4.5
되도록 실제 환경과 유사한 테스트 케이스를 만들기 위해 `SpringBootTest`를 사용했습니다. 또한 독립적인 테스트를 위해서 해당 클래스에서 `@BeforeEach`을 활용해 더미 데이터를 생성해주었습니다. 이 때문에 조금 더 지저분해보이네요 ㅠㅠㅠ
가능한 모든 경우의 수를 테스트하려고 했습니다. 또한 중요한 순서 수정 로직 같은 경우에는 되도록이면 메서드 추출을 하지 않았습니다. 로직이 매우 복잡하기 때문에 이부분은 펼쳐놓는 것이 이해하기에 조금 더 편할 것이라고 생각했습니다! 월요일날 한 번 더 얘기 나눠봤으면 좋겠네요 ㅎㅎㅎ

[BE] fix: 카테고리 및 글 순서 이동 수정

---

backend/src/main/java/org/donggle/backend/ui/common/RefreshTokenAuthInterceptor.java

- close #484 
- RefreshTokenAuthInterceptor에서 요청 메서드가 OPTIONS일 경우 true 반환

[BE] fix: 토큰 재발행 Preflight 요청시 터지는 예외 수정

---

frontend/src/components/@common/Accordion/AccordionTitle.tsx
frontend/src/components/Category/Category/Category.tsx
frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx

- close #492 
- 0.5 -> 0.5
- 카테고리 이름이 길면 카테고리를 열 수 있는 버튼이 보이지 않는 현상 수정
| 전 | 후 |
| ------------ | ------------- |
| <img width="293" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/3dd848b8-fcae-4c97-9b72-cba9e8a8c36c"> | <img width="290" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/e81f510e-f7d6-4d35-bc12-a089c1be383d"> |
- 글 제목이 길어지면 글 제목 수정하기 버튼이 작아지는 현상 수정
| 전 | 후 |
| ------------ | ------------- |
| <img width="640" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/cb1c04f4-286a-4554-a027-bd4797b6c416"> | <img width="634" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/f9a3ba87-151f-48eb-9f85-2ed92ab6a213"> |

[FE] fix: 카테고리 이름이 길면 카테고리를 열 수 있는 버튼이 보이지 않는 현상 수정

---

frontend/src/components/WritingTable/WritingTable.tsx

- close #494
- 0.1 -> 0.1
전체 글/카테고리 모두 생성날짜-발행한 플랫폼 순서로 바꿨습니다. 
이미지는 마지막으로 들어가는게 더 자연스러운 것 같아서 플랫폼을 마지막으로 뺐습니다!

[FE] fix: 발행정보와 발행 플랫폼 헤더와 데이터 위치 조정

---

frontend/src/components/WritingViewer/WritingViewer.tsx

- close #496 
- 0.3 -> 0.3
| 전 | 후 | 노션 원본 |
| ------------ | ------------- | ------------- |
| <img width="511" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/3222be98-6537-4b69-8b13-e6ab1bf2937e"> | <img width="556" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/903ace5b-002f-4de2-a63f-7de066b2d814"> | <img width="559" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/5ad04c1d-af74-4208-901b-9fc5d1fb2c8e"> |
1. p태그 내에서 행간 크기가 너무 달라붙어 있어서 노션과 유사하게 좀더 넓게 조정했습니다.
2. `develop 브랜치와 머지 시 ~~~`, `사실 실제 API와의 테스트`로 시작하는 문장 위에 원래 한 줄 공백이 있는데 기존에는 공백이 무시되던 현상을 수정했습니다.
원인은 원래 한 줄 공백이 빈 p태그로 오게 되는데(`<p></p>`) 이 경우 margin 겹침(상쇄) 현상 때문에 공백이 무시되고 있던 것이어서 margin을 padding으로 바꾸어 해결하였습니다.

[FE] fix: 글에서 빈 블락이 렌더링되지 않는 현상 수정

---

frontend/src/components/Category/WritingList/useDeleteWritings.ts
frontend/src/components/TrashCanTable/useRestoreDeletedWritings.ts

- close #512 
- 1 -> 0.5
현재 mocking으로만 작업해서 제대로 동작하는지 확인은 되지 않지만, 현재는 React query devtools로 확인한 결과 원하는대로 refetch 하는 것을 확인했습니다.
추후 쿠마의 msw가 머지되면 제대로 테스트한 뒤에 다시 리뷰 요청하겠습니다.
https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/0aeb5f2d-a975-4478-af6c-a2d9348aa652

[FE] fix: 글 복구, 글 삭제 관련 invalidateQueries 설정

---

frontend/src/components/HomeTable/HomeTable.tsx
frontend/src/components/WritingTable/WritingTable.tsx

[FE] refactor: 글 테이블에 발행한 블로그 플랫폼 여부에 따라 높이가 다른 현상 수정

---

frontend/src/components/Category/Category/Category.tsx
frontend/src/components/Category/WritingList/WritingList.tsx

- close #522 
- 0.5 -> 1
reflow repaint를 피하기 위해
이전에 호버하면 display: none 이 display: flex 로 변경되는 부분을 opacity: 0 -> opacity: 0.99로 수정했습니다.
또한 position도 absolute로 수정했습니다~!
https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/1966425c-b31e-4be6-8def-b44c5e9667b1

[FE] fix: 빈 공간 클릭 시 이동되게 수정

---

frontend/src/components/TrashCanTable/TrashCanTable.tsx
frontend/src/components/TrashCanTable/useDeletePermanentWritings.ts
frontend/src/components/TrashCanTable/useRestoreDeletedWritings.ts
frontend/src/components/TrashCanTable/useTrashCanTable.ts

- close #511 
- 0.5 -> 0.5
Input 의 checked 속성이 defaultChecked로 수정되어 있더라구요.
이 부분에 checked를 추가하여 버그 해결했습니다.
https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/92574db8-4e82-4791-ad5f-5d44c8c70ad2

[FE] fix: 체크박스 오류 해결

---

frontend/src/apis/blogs.ts
frontend/src/assets/icons/category.svg
frontend/src/assets/icons/index.ts
frontend/src/components/PublishingPropertySection/PublishingPropertyStyle.ts
frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
frontend/src/components/PublishingPropertySection/useTistoryPublishingPropertySection.ts
frontend/src/components/PublishingSection/PublishingSection.tsx
frontend/src/constants/apis/url.ts
frontend/src/hooks/queries/blogs/useTistoryCategories.ts
frontend/src/types/apis/blogs.ts

- close #477
- close #515
- 티스토리 발행 시 카테고리 선택 기능
- <img width="305" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/ebcaf597-6265-439b-b355-201869a74655">
- 발행 탭에 연결 블로그 없는 경우 마이 페이지로 이동하는 버튼 추가
- 모든 블로그를 연결하지 않은 경우
- 하나만 연결한 경우
- 모두 연결한 경우
- 6 + 2
1. 카테고리 select `width`를 `100%`로 고정하고 싶은데 어떻게 해야할 지 모르겠네요ㅠ
2. <S.TistoryCategorySelect
onChange={(e: ChangeEvent<HTMLSelectElement>) => setCategoryId(e.target.value)}
disabled={isCategoryLoading}
> 에서 onChange={(e: ChangeEvent<HTMLSelectElement>) => setCategoryId(e.target.value)} 이 부분이 의아할 수 있는데, styled로 select 태그를 쓰니까 `e` 타입을 감지못하더라구요. 그래서 저렇게 명시해두었습니다.

[FE] feat: 티스토리 발행 카테고리 선택 기능, 발행 탭 블로그 연결 버튼 추가

---

backend/src/main/java/org/donggle/backend/application/repository/BlockRepository.java
backend/src/main/java/org/donggle/backend/application/repository/BlogWritingRepository.java
backend/src/main/java/org/donggle/backend/application/repository/CategoryRepository.java
backend/src/main/java/org/donggle/backend/application/repository/MemberCredentialsRepository.java
backend/src/main/java/org/donggle/backend/application/repository/MemberRepository.java
backend/src/main/java/org/donggle/backend/application/repository/StyleRepository.java
backend/src/main/java/org/donggle/backend/application/repository/TokenRepository.java
backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
backend/src/main/java/org/donggle/backend/application/service/blog/PublishService.java
backend/src/main/java/org/donggle/backend/application/service/category/CategoryService.java
backend/src/main/java/org/donggle/backend/application/service/member/MemberService.java
backend/src/main/java/org/donggle/backend/application/service/writing/WritingService.java
backend/src/main/java/org/donggle/backend/domain/member/Member.java
backend/src/main/java/org/donggle/backend/domain/writing/Writing.java
backend/src/main/java/org/donggle/backend/domain/writing/block/NormalBlock.java
backend/src/main/java/org/donggle/backend/infrastructure/client/medium/MediumConnectionClient.java
backend/src/main/java/org/donggle/backend/infrastructure/client/notion/NotionConnectionClient.java
backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClient.java
backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryConnectionClient.java
backend/src/main/java/org/donggle/backend/ui/MemberController.java
backend/src/main/resources/application.yml
backend/src/test/java/org/donggle/backend/TestFixtures.java
backend/src/test/java/org/donggle/backend/application/service/MemberServiceTest.java

- close #487 
- 삭제 로직 구현
- 삭제에 대한 테스트 케이스 구현
- 1 -> 4
처음에 어떻게 삭제를 해야할지 많이 고민을 했습니다. 초반에 많이 해맸는데 제가 마주했던 문제는 다음과 같습니다.
1. 무결성 제약 조건 때문에 삭제해야 하는 엔티티들 간의 순서가 있었습니다.
2. 그 중에서 `Writing`과 `Category`는 맨 앞부터 하나씩 차례로 지워나가야만 했던 것도 유의해야 했습니다.
3. 이전의 쿼리에서 `DELETE`를 하더라도 그 즉시 `flush()`되는 것이 아니었기에 데이터의 정합성 문제(쓰기 지연 저장소에 있는 쿼리들이 반영되지 않는 문제)가 있었습니다.
4. `cascade = CascadeType.REMOVE`를 최대한 사용해 하나의 엔티티를 지우면 연관된 모든 엔티티를 지우도록 하려고 했지만, 결국 이를 사용하려면 연관된 엔티티 모두를 영속성 컨텍스트에 올려놔야만 가능한 일이었기에, 불필요한 조회 쿼리가 발생하기도 했습니다.
따라서 현재에는 벌크성 쿼리를 통해 영속성 컨텍스트와 별개로 데이터베이스에 바로 쿼리를 날리도록 하였습니다. 이때 `@Modifying`을 사용했는데 이에 대한 정리는 [동글 블로그](https://medium.com/dong-gle/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%82%AD%EC%A0%9C-cdd21d7d1e67)에 올려놨습니다.
4번 문제는 조금 더 알아보고, 테스트해보고 공유할게요!

[BE] refactor: 회원 탈퇴 로직 수정

---

backend/src/main/java/org/donggle/backend/infrastructure/client/notion/NotionApiClient.java

- close #468, #545 
- 0
- 개인 Notion Token을 이용해 응답 테스트를 하였고 정상 작동을 확인했습니다~

[BE] fix: 노션 파싱 버그 수정

---

frontend/package.json
frontend/src/hooks/@common/useCodeHighlight.ts
frontend/src/mocks/data/writingPage.ts
frontend/webpack.common.js
frontend/yarn.lock

- close #549
- `prismjs` 동적 import 방식을 개선
- `prismjs`의 [autoloader](https://prismjs.com/plugins/autoloader/) 이용
-  `autoloader` 에게 알려줄 `prismjs/components`(언어 스타일링 패키지)를 따로 빼서 번들링하기 위해 `copyWebpackPlugin`을 이용
- 4 + 4
- 흠.. 생각보다 어려웠네요.
- 이제 코드블럭에서 약 300개의 언어를 지원합니다!

[FE] fix: `prismjs` dynamic import 방식 개선

---

backend/src/main/java/org/donggle/backend/infrastructure/client/tistory/TistoryApiClient.java
backend/src/main/java/org/donggle/backend/ui/BlogController.java
backend/src/main/java/org/donggle/backend/ui/response/TistoryCategoryListResponse.java

[BE] fix: 티스토리 카테고리가 없는 사용자에 대한 예외 처리 기능 구현

---

backend/src/main/java/org/donggle/backend/application/service/category/CategoryService.java

- close #557 
- `CategoryService`의 `modifyCategoryOrder` 메서드에 `flush()` 호출 추가
- 0.1 -> 0.1
-

[BE] fix: `CategoryService`의 `modifyCategoryOrder`에서 `flush()` 호출 추가

---

.github/workflows/fe-test-e2e.yml
frontend/cypress/e2e/main-page.cy.ts
frontend/cypress/e2e/my-page.cy.ts
frontend/cypress/e2e/space-page.cy.ts
frontend/cypress/e2e/trashcan-page.cy.ts
frontend/cypress/e2e/writing-page.cy.ts
frontend/cypress/tsconfig.json
frontend/package.json
frontend/src/components/Category/WritingList/WritingList.tsx
frontend/src/components/ConnectionSection/ConnectionSection.tsx
frontend/src/components/TrashCanTable/TrashCanTable.tsx
frontend/src/mocks/data/trashCanPage.ts
frontend/tsconfig.json
frontend/yarn.lock

- close #506
- 테스트용 서버를 모킹으로 변경
- 테스트 작성
- 8 + 8
- redirect가 필요한 로그인, 연결 테스트가 잘 동작을 하지 않더라구요.. 해결방법을 몇시간이나 찾아보다 결국 찾지 못했습니다ㅠ
- 로그인, 연결테스트가 잘 된다면 간접적으로나마 테스트를 할 수 있는건데 아쉽습니다. (일단 주석처리 해놨어요)
- 실제 서버 api에 의존적인 e2e였다가 이제 모킹으로 바꿨으니, 이제 통합 테스트라고 불러야할까요? 아커 파인의 생각이 궁금합니다. (좀 찾아봤는데, 모킹한 e2e라고 불러도 될 것 같네요. 브랜치 명 잘못지었네요ㅠ)
- msw의 모든 요청에 delay가 어느정도 들어가기 때문에 cypress에서 wait(1000) 코드가 많이보입니다. 이것때문에 테스트가 좀 오래걸리는데, delay시간을 아예 없앨까요.. 아니면 시간만 좀 줄일까요? (delay를 넣은 이유는 로딩 상태일 때 대체 렌더링을 눈으로 보고싶어서 넣었습니다)

[FE] test: 모킹 서버를 이용한 cypress 테스트 추가

---

backend/src/main/java/org/donggle/backend/application/service/auth/AuthFacadeService.java
backend/src/main/java/org/donggle/backend/exception/authentication/ExpiredRefreshTokenException.java
backend/src/main/java/org/donggle/backend/exception/authentication/InvalidRefreshTokenException.java
backend/src/main/java/org/donggle/backend/ui/AuthController.java
backend/src/main/java/org/donggle/backend/ui/common/WebMvcConfig.java
backend/src/test/java/org/donggle/backend/application/service/auth/AuthFacadeServiceTest.java
backend/src/test/java/org/donggle/backend/ui/AuthControllerTest.java

- close #562 
- 로그아웃 시 ArgumentResolver가 동작하지 않도록 수정
- 로그아웃 시 refreshToken이 없는 케이스 핸들링
- refreshTokn 재발급 요청시 refreshToken이 없는 케이스 핸들링
- 1 -> 1

[BE] refactor: logout 및 reissueRefreshToken 요청시 리프래시 토큰이 없는 경우 추가 핸들링

---

frontend/src/components/GoToPageLink/GoToPageLink.tsx
frontend/src/styles/reset.ts

- close #565 
- 0.5 -> 0.5
- 변경 전
- 변경 후

[FE] design: reset.css 에 a:link, a:visit 컬러 스타일 추가

---

frontend/src/components/@common/Menu/Item.tsx
frontend/src/components/HelpMenu/HelpMenu.tsx

- close #559 
- 0.5 -> 0.5
- border-bottom을 주었어야 했는데, 실수로 border를 주어서 width 차이가 있었습니다. 또한 border-bottom으로 주니 높이 차이가 1px이 나서, box-shadow로 경계선 효과를 줬습니다. 현재는 width, height 모두 동일합니다

[FE] refactor: 도움말 디자인 바꾸기

---

frontend/package.json
frontend/src/App.tsx
frontend/src/components/LeftSideBar/LeftSideBar.tsx
frontend/src/globalState/index.ts
frontend/src/hooks/@common/useMediaQuery.ts
frontend/src/pages/Layout/Layout.tsx
frontend/src/styles/layoutStyle.ts
frontend/yarn.lock

- close #591
- 3 -> 5
레이아웃에 큰 영향을 주는 컴포넌트를 `Drawer`로 선정을 하였습니다.
* 선정한 이유
현재 동글 스페이스 페이지에 사이드바가 존재하고, 글 페이지의 경우 오른쪽 사이드바도 추가됩니다.
때문에 모바일 환경에서 보면 레이아웃이 상당히 깨지는 모습을 확인할 수 있습니다.
따라서 태블릿, 모바일 환경에서는 기존 사이드바들이 Drawer형태로 나타나도록 변경하기로 했습니다.
분리한 Drawer 컴포넌트는 NPM에 현재 배포하여 사용하고 있습니다.
| 변경 전 | 변경 후 |
| ------| -------|
|<img width="589" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/99b0cfdf-dac3-4bab-b55b-2d4c4a166476"> | ![Oct-18-2023 17-05-00](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/0b415e00-0971-463c-82f3-4be4afcb8795) |

[FE] refactor: 레이아웃에 큰 영향을 주는 `Drawer` 컴포넌트를 분리하여 반응형 사이드바 구현

---

backend/src/test/java/org/donggle/backend/application/service/PublishFacadeServiceTest.java

- close #600
- entitymanager mocking

[BE] fix: PublishFacadeServiceTest에서 EntityManager가 mocking 되지 않아 터지는 예외 수정

---

frontend/cypress.config.ts
frontend/cypress/constants/url.ts
frontend/cypress/e2e/space-page.cy.ts
frontend/cypress/e2e/writing-page.cy.ts
frontend/cypress/overrideHandler/writing.ts
frontend/cypress/tsconfig.json
frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx
frontend/src/hooks/@common/useControlledInput.ts
frontend/src/mocks/browser.ts
frontend/src/mocks/data/category.ts
frontend/src/mocks/handlers/writing.ts
frontend/src/types/msw.d.ts

- close #585
수정 전
https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/61c6323d-ba74-4e3d-8678-570c465515ce
수정 후
https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/d9e50cb6-72d3-4f59-a187-2ff692fd4b27
- 글 제목 수정할 때 낙관적 업데이트 적용
- 글 제목 수정 시 깜빡임 현상 해결
- 글 제목 수정 실패 테스트 추가 (msw 오버라이딩 환경설정 및 함수 추가)
- 6 + 6
-

[FE] refactor: 글 제목 수정 낙관적 업데이트 구현

---

.github/workflows/build-be-prod.yml
.github/workflows/build-fe-prod.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/fe-test-e2e.yml

- close #579 
- deploy-prod.yml에서 fe,be build가 끝날 경우 deploy가 실행되도록 변경
- deploy.sh가 실행되도록 추가
- -0.5
- fe,be-build가 동시에 실행되며 둘다 끝나야 deploy-prod.yml이 실행되도록 변경했습니다.

[ALL] chore: prod cicd actions 실행 순서 변경 및 deploy.sh 실행 추가

---

frontend/.storybook/preview.tsx
frontend/cypress/e2e/main-page.cy.ts
frontend/cypress/e2e/trashcan-page.cy.ts
frontend/src/App.tsx
frontend/src/components/Category/Category/Category.stories.tsx
frontend/src/components/Category/Section/Section.stories.tsx
frontend/src/components/Category/WritingList/WritingList.stories.tsx
frontend/src/components/WritingTable/WritingTable.stories.tsx
frontend/src/components/WritingViewer/WritingViewer.stories.tsx

- close #606 
- 스토리북에 react-query 지원 (msw로 통합)
- cypress 테스트 정상화
- 2 -> 1
-

[FE] fix: 프론트엔드 스토리북 & cypress 테스트 깨지는 부분 수정

---

frontend/.storybook/preview.tsx
frontend/cypress/e2e/main-page.cy.ts
frontend/cypress/e2e/trashcan-page.cy.ts
frontend/src/App.tsx
frontend/src/components/Category/Category/Category.stories.tsx
frontend/src/components/Category/Section/Section.stories.tsx
frontend/src/components/Category/WritingList/WritingList.stories.tsx
frontend/src/components/WritingTable/WritingTable.stories.tsx
frontend/src/components/WritingViewer/WritingViewer.stories.tsx

- close #607
- 스토리북에 react-query 지원 (msw로 통합)
- cypress 테스트 정상화
- 2 -> 1
-

[FE] fix: 프론트엔드 스토리북 & cypress 테스트 깨지는 부분 수정 #607

---

.github/workflows/build-be-dev.yml
.github/workflows/build-be-prod.yml
.github/workflows/build-fe-dev.yml
.github/workflows/build-fe-prod.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
backend/Dockerfile-dev
compose-blue.yml
compose-green.yml

- close #611
- 새로운 EC2 서버 설정
- Action Runner 설정
- Action Script 수정
- Docker Compose 설정 변경

chore: GitHub Action 스크립트를 이전한 인프라에 맞게 수정

---

frontend/src/components/ConnectionSection/ConnectionSection.tsx
frontend/src/components/PublishingSection/PublishingSection.tsx
frontend/src/pages/MyPage/MyPage.tsx

[FE] fix: 티스토리 API 종료로 인한 퍼블리싱 버튼, 블로그 연결 버튼 제거
